// GENERATED by scripts/sync-tokens.mjs from tokens/primitive.scales.json. Do not edit.
/**
 * The space scale in CSS px, for props that take a number instead of a CSS length
 * (Radix `sideOffset`, `collisionPadding`). Same steps as `--space-*`.
 */
export const space = {
  '0': 0,
  '1': 4,
  '2': 8,
  '3': 12,
  '4': 16,
  '5': 20,
  '6': 24,
  '8': 32,
  '10': 40,
  '12': 48,
  '16': 64,
  '20': 80,
  '24': 96,
  '32': 128,
  '40': 160,
  '0.5': 2,
  '1.5': 6,
  '2.5': 10,
  'px': 1,
} as const;

/** The viewport breakpoints in CSS px, for `matchMedia` (`(min-width: ${breakpoint.sm}px)`). */
export const breakpoint = {
  'xs': 320,
  'sm': 672,
  'md': 1056,
  'lg': 1312,
  'xl': 1584,
} as const;
