// GENERATED by scripts/sync-tokens.mjs from tokens/primitive.scales.json. Do not edit.
/**
 * The SSX motion scale in the units GSAP takes: durations and stagger intervals
 * in SECONDS, curves as cubic-bezier control points, distances in rem (the same
 * rem the CSS tokens are written in). Same steps as `--motion-*`.
 */
export const motionTokens = {
  duration: {
    instant: 0.1,
    fast: 0.15,
    normal: 0.25,
    slow: 0.35,
    slower: 0.5,
    slowest: 0.8,
  },
  stagger: {
    tight: 0.03,
    base: 0.06,
  },
  easing: {
    productiveInOut: [0.2, 0, 0.38, 0.9] as const,
    productiveEntrance: [0, 0, 0.38, 0.9] as const,
    productiveExit: [0.2, 0, 1, 0.9] as const,
    expressiveInOut: [0.4, 0.14, 0.3, 1] as const,
    expressiveEntrance: [0, 0, 0.3, 1] as const,
    overshoot: [0.34, 1.56, 0.64, 1] as const,
    linear: [0, 0, 1, 1] as const,
  },
  offset: {
    enter: '0.75rem',
    reveal: '1.5rem',
    lift: '0.125rem',
  },
  scale: {
    enter: 0.96,
    pulse: 0.82,
    beat: 1.15,
    ring: 2.5,
    press: 0.98,
    pressSurface: 0.99,
  },
  viewport: {
    enter: '10%',
  },
} as const;
