/**
 * Copies the generated token stylesheet out of the Python build into the React
 * package (plus, for the Storybook Foundations pages only, the contrast audit
 * and the DTCG token sources), so `src/styles/` has a real file to import without the package
 * reaching outside its own root (which breaks once it is published).
 *
 * The copy is GENERATED. It is never hand-edited, and it is never the source of
 * truth — `scripts/build.py` in the repo root is. Run `npm run build` at the
 * repo root first if the tokens have changed.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');

const sources = [
  {
    from: resolve(repoRoot, 'dist/tokens.css'),
    to: resolve(here, '..', 'src/styles/tokens.generated.css'),
    required: true,
  },
  // Storybook's Foundations pages (src/foundations/) read these, never the
  // package: the contrast gate's report, and the DTCG sources for the token
  // descriptions. Optional: a standalone checkout keeps the committed copies.
  {
    from: resolve(repoRoot, 'dist/audit.txt'),
    to: resolve(here, '..', 'src/foundations/_generated/audit.txt'),
    required: false,
  },
  {
    from: resolve(repoRoot, 'tokens/semantic.color.json'),
    to: resolve(here, '..', 'src/foundations/_generated/semantic.color.json'),
    required: false,
  },
  {
    from: resolve(repoRoot, 'tokens/primitive.scales.json'),
    to: resolve(here, '..', 'src/foundations/_generated/primitive.scales.json'),
    required: false,
  },
];

let copied = 0;
for (const { from, to, required } of sources) {
  if (!existsSync(from)) {
    const message = `sync-tokens: missing ${from}. Run \`npm run build\` at the repo root first.`;
    // Standalone checkout (this package without the design-system repo around it):
    // the committed copy is the tokens. Keep it rather than failing.
    if (existsSync(to)) {
      console.warn(`sync-tokens: ${from} not found; using the committed ${to}.`);
      continue;
    }
    if (required) {
      console.error(message);
      process.exit(1);
    }
    console.warn(message);
    continue;
  }
  mkdirSync(dirname(to), { recursive: true });
  copyFileSync(from, to);
  copied += 1;
  console.log(`sync-tokens: ${from} -> ${to}`);
}

console.log(`sync-tokens: ${copied} file(s) synced.`);

// The space scale as NUMBERS, for the few APIs that take a pixel number rather than a
// CSS length (Radix `sideOffset`, `collisionPadding`). Generated from the token SOURCE,
// so a component never writes `sideOffset={4}` and hopes it still means --space-1.
// Standalone checkout: the committed copy stands, as above.
const scalesSource = resolve(repoRoot, 'tokens/primitive.scales.json');
const scaleOut = resolve(here, '..', 'src/lib/scale.generated.ts');
if (existsSync(scalesSource)) {
  const { space, breakpoint } = JSON.parse(readFileSync(scalesSource, 'utf8'));
  const px = (group) =>
    Object.entries(group)
      .filter(([k, v]) => !k.startsWith('$') && /^\d+(\.\d+)?px$/.test(String(v?.$value)))
      .map(([k, v]) => `  '${k}': ${parseFloat(v.$value)},`);
  const entries = px(space);
  const breakpoints = px(breakpoint);
  writeFileSync(
    scaleOut,
    [
      '// GENERATED by scripts/sync-tokens.mjs from tokens/primitive.scales.json. Do not edit.',
      '/**',
      ' * The space scale in CSS px, for props that take a number instead of a CSS length',
      ' * (Radix `sideOffset`, `collisionPadding`). Same steps as `--space-*`.',
      ' */',
      'export const space = {',
      ...entries,
      '} as const;',
      '',
      '/** The viewport breakpoints in CSS px, for `matchMedia` (`(min-width: ${breakpoint.sm}px)`). */',
      'export const breakpoint = {',
      ...breakpoints,
      '} as const;',
      '',
    ].join('\n'),
  );
  console.log(`sync-tokens: ${scalesSource} -> ${scaleOut}`);

  // The motion scale for GSAP (src/motion). GSAP takes seconds and numbers, CSS
  // takes custom properties; both read the same token source, so a retuned
  // duration or curve moves the CSS keyframes and the GSAP tweens together.
  const { motion } = JSON.parse(readFileSync(scalesSource, 'utf8'));
  const camel = (k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  const leaves = (group, map) =>
    Object.entries(group)
      .filter(([k]) => !k.startsWith('$'))
      .map(([k, v]) => `    ${/^[a-z][a-zA-Z0-9]*$/.test(camel(k)) ? camel(k) : `'${k}'`}: ${map(v.$value)},`);
  const seconds = (v) => {
    const m = String(v).match(/^(\d+(?:\.\d+)?)ms$/);
    if (!m) throw new Error(`sync-tokens: motion duration ${v} is not in ms`);
    return String(Number(m[1]) / 1000);
  };
  const rem = (v) => {
    const m = String(v).match(/^(\d+(?:\.\d+)?)px$/);
    if (!m) throw new Error(`sync-tokens: motion offset ${v} is not in px`);
    return `'${Number(m[1]) / 16}rem'`;
  };
  const motionOut = resolve(here, '..', 'src/motion/tokens.generated.ts');
  mkdirSync(dirname(motionOut), { recursive: true });
  writeFileSync(
    motionOut,
    [
      '// GENERATED by scripts/sync-tokens.mjs from tokens/primitive.scales.json. Do not edit.',
      '/**',
      ' * The SSX motion scale in the units GSAP takes: durations and stagger intervals',
      ' * in SECONDS, curves as cubic-bezier control points, distances in rem (the same',
      ' * rem the CSS tokens are written in). Same steps as `--motion-*`.',
      ' */',
      'export const motionTokens = {',
      '  duration: {',
      ...leaves(motion.duration, seconds),
      '  },',
      '  stagger: {',
      ...leaves(motion.stagger, seconds),
      '  },',
      '  easing: {',
      ...leaves(motion.easing, (v) => `[${v.join(', ')}] as const`),
      '  },',
      '  offset: {',
      ...leaves(motion.offset, rem),
      '  },',
      '  scale: {',
      ...leaves(motion.scale, (v) => String(v)),
      '  },',
      '  viewport: {',
      ...leaves(motion.viewport, (v) => `'${v}'`),
      '  },',
      '} as const;',
      '',
    ].join('\n'),
  );
  console.log(`sync-tokens: ${scalesSource} -> ${motionOut}`);
} else if (!existsSync(scaleOut)) {
  console.error(`sync-tokens: missing ${scalesSource} and no committed ${scaleOut}.`);
  process.exit(1);
}
